/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Star.gltf -o src/components/Star.jsx -r public
Star by Kay Lousberg (https://market.pmnd.rs/model/star)
*/

import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import React, { useRef } from "react";

export function Star(props) {
  const { nodes, materials } = useGLTF("/models/Heart.glb");
  const ref = useRef()
  useFrame(()=>{
    ref.current.rotation.y += 0.01
  }
  )
  return (
    <primitive object={nodes.Heart} {...props} dispose={null} ref={ref}/>
      
  );
}

useGLTF.preload("/models/Heart.glb");
